pep8:
    options:
        max-line-length: 120

pydocstyle:
    run: true

pyflakes:
    run: false

pylint:
    disable:
        -   import-outside-toplevel
        -   inconsistent-return-statements
        -   too-many-arguments
