version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.9'
  apt_packages:
  - gfortran      # This is necessary for the `sisl` dependency of `aiida-siesta`

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - all_plugins
    - docs

sphinx:
  builder: html
  fail_on_warning: true
