[build-system]
requires = ["setuptools>=40.8.0", "wheel", "fastentrypoints~=0.12"]
build-backend = "setuptools.build_meta"

[tool.isort]
force_sort_within_sections = true
include_trailing_comma = true
line_length = 120
multi_line_output = 3

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "import-outside-toplevel",
    "inconsistent-return-statements",
    "too-many-arguments",
    "bad-continuation",
    "duplicate-code",
    "no-member",
    "too-few-public-methods",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore::DeprecationWarning:abipy:",
    "ignore::DeprecationWarning:ase:",
    "ignore::DeprecationWarning:frozendict:",
    "ignore::DeprecationWarning:past:",
    "ignore::DeprecationWarning:sqlalchemy_utils:",
    "ignore::DeprecationWarning:reentry:",
    "ignore::DeprecationWarning:pkg_resources:",
    "ignore::PendingDeprecationWarning:monty:",
    "ignore::PendingDeprecationWarning:pymatgen:",
    "ignore::PendingDeprecationWarning:ruamel:",
]

[tool.yapf]
align_closing_bracket_with_visual_indent = true
based_on_style = "google"
coalesce_brackets = true
column_limit = 120
dedent_closing_brackets = true
indent_dictionary_value = false
split_arguments_when_comma_terminated = true
